#!/usr/bin/env python3
"""Unprivileged researcher-side probe for Phase A process-isolation CI."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--hidden", required=True)
    ap.add_argument("--evaluator-source", required=True)
    ap.add_argument("--candidate-out", required=True)
    ap.add_argument("--report-out", required=True)
    args = ap.parse_args()

    hidden_path = Path(args.hidden)
    evaluator_path = Path(args.evaluator_source)

    report = {
        "uid": os.geteuid(),
        "hidden_path_was_disclosed": True,
        "hidden_readable": None,
        "hidden_read_error": None,
        "evaluator_source_readable": False,
        "evaluator_source_writable": None,
        "evaluator_source_write_error": None,
        "environment_keys": sorted(os.environ),
    }

    try:
        hidden_path.read_text(encoding="utf-8")
        report["hidden_readable"] = True
    except Exception as exc:
        report["hidden_readable"] = False
        report["hidden_read_error"] = type(exc).__name__

    try:
        src = evaluator_path.read_bytes()
        report["evaluator_source_readable"] = True
        report["evaluator_source_sha256"] = hashlib.sha256(src).hexdigest()
    except Exception as exc:
        report["evaluator_source_read_error"] = type(exc).__name__

    try:
        with evaluator_path.open("ab") as f:
            f.write(b"\n# researcher-write-probe\n")
        report["evaluator_source_writable"] = True
    except Exception as exc:
        report["evaluator_source_writable"] = False
        report["evaluator_source_write_error"] = type(exc).__name__

    candidate = {
        "candidate_id": "PROCESS-ISOLATION-PROBE",
        "feature": {"source": "feature_a", "transform": "identity", "lag": 0},
        "operator": "gt",
        "threshold": 0.0,
        "side": "long",
        "position_size": 0.5,
        "researcher_note": "generated by unprivileged process without hidden data",
    }
    Path(args.candidate_out).write_text(
        json.dumps(candidate, sort_keys=True, separators=(",", ":")),
        encoding="utf-8",
    )
    Path(args.report_out).write_text(
        json.dumps(report, sort_keys=True, indent=2),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
